# Generated by Django 3.0.10 on 2024-12-15 11:48

from django.db import migrations, models
import shortener_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasedURL',
            fields=[
                ('alias', models.CharField(default=shortener_app.utils.get_random_alias, max_length=8, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
